version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_DATABASE_URL: ${POSTGRES_DATABASE_URL}
        PORT: ${PORT}
    ports:
      - '${PORT}:${PORT}'
    environment:
      - BASE_URL=${BASE_URL}
      - TOKEN_DEVELOPMENT=${TOKEN_DEVELOPMENT}
      - ALLOWED_URLS=${ALLOWED_URLS}
      - MONGO_DATABASE_URL=${MONGO_DATABASE_URL}
      - POSTGRES_DATABASE_URL=${POSTGRES_DATABASE_URL}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
      - PORT=${PORT}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - REFRESH_TOKEN_SECRET_KEY=${REFRESH_TOKEN_SECRET_KEY}
      - TOKEN_EXPIRATION_TIME=${TOKEN_EXPIRATION_TIME}
      - REFRESH_TOKEN_EXPIRATION_TIME=${REFRESH_TOKEN_EXPIRATION_TIME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - mongo
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  mongo-data:
    driver: local