version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_DATABASE_URL: ${POSTGRES_DATABASE_URL}
        PORT: ${PORT}
    ports:
      - '${PORT}:${PORT}'
    environment:
      - BASE_URL=${BASE_URL}
      - TOKEN_DEVELOPMENT=${TOKEN_DEVELOPMENT}
      - ALLOWED_URLS=${ALLOWED_URLS}
      - MONGO_DATABASE_URL=${MONGO_DATABASE_URL}
      - POSTGRES_DATABASE_URL=${POSTGRES_DATABASE_URL}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
      - PORT=${PORT}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - REFRESH_TOKEN_SECRET_KEY=${REFRESH_TOKEN_SECRET_KEY}
      - TOKEN_EXPIRATION_TIME=${TOKEN_EXPIRATION_TIME}
      - REFRESH_TOKEN_EXPIRATION_TIME=${REFRESH_TOKEN_EXPIRATION_TIME}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - app-network
    restart: always
    command: ['nginx', '-g', 'daemon off;']

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"
    networks:
      - app-network
    depends_on:
      - nginx

networks:
  app-network:
    driver: bridge
