version: '3.8'

services:
  emprestai-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_DATABASE_URL: ${POSTGRES_DATABASE_URL}
        PORT: ${PORT}
    ports:
      - '${PORT}:${PORT}'
    environment:
      - BASE_URL=${BASE_URL}
      - TOKEN_DEVELOPMENT=${TOKEN_DEVELOPMENT}
      - ALLOWED_URLS=${ALLOWED_URLS}
      - MONGO_DATABASE_URL=${MONGO_DATABASE_URL}
      - POSTGRES_DATABASE_URL=${POSTGRES_DATABASE_URL}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
      - PORT=${PORT}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - REFRESH_TOKEN_SECRET_KEY=${REFRESH_TOKEN_SECRET_KEY}
      - TOKEN_EXPIRATION_TIME=${TOKEN_EXPIRATION_TIME}
      - REFRESH_TOKEN_EXPIRATION_TIME=${REFRESH_TOKEN_EXPIRATION_TIME}
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true